apiVersion: apps/v1
kind: Deployment
metadata:
  name: vue-storefront
spec:
  selector:
    matchLabels:
      app: vue-storefront
  template:
    metadata:
      labels:
        app: vue-storefront
    spec:
      containers:
      - name: vue-storefront
        image: docker.pkg.github.com/it-jonction/vue-storefront/vue-storefront:0.0.1
        envFrom:
        - configMapRef:
            name: vue-storefront-config
        ports:
        - containerPort: 3000
        volumeMounts:
        - mountPath: /var/www/var
          name: code
          subPath: var
        - mountPath: /var/www/dist
          name: dist
      volumes:
      - name: code
        emptyDir:
          medium: Memory
      - name: dist
        emptyDir:
          medium: Memory
